#!/bin/bash

yad --button="Cancel:1" --button="Punch in:0" --text="TIDE Punch" --text-align=center
exval=$?
case $exval in
    # 1) notify-send "You pressed Cancel";;
    0) xdg-open https://app.propertime.co.il/MonthlyTimesheet.aspx && open-i3-wksp 🌎 I;;
    #  252) notify-send "You pressed ESCAPE key or closed the window.";;
esac

exit
